"""Generate DATA_PROFILE.md from the bundled sample dataset (Build Plan phase 0.3).

Run from the project root:  .venv/bin/python scripts/profile_data.py
"""
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(ROOT))

import pandas as pd  # noqa: E402

from core.ingestion import DEMO_PATH, load_csv  # noqa: E402


def main() -> None:
    raw = load_csv(DEMO_PATH)
    dates = pd.to_datetime(raw["Order Date"], errors="coerce", dayfirst=True)
    sales = pd.to_numeric(raw["Sales"], errors="coerce")

    lines: list[str] = []
    add = lines.append

    add("# Data Profile — Superstore Sales (bundled sample)")
    add("")
    add(f"Source file: `data/{DEMO_PATH.name}` · "
        "mirror of Kaggle `rohitsahoo/sales-forecasting`.")
    add("")
    add(f"- **Rows:** {len(raw):,}")
    add(f"- **Columns:** {raw.shape[1]}")
    add(f"- **Date range (Order Date, day-first):** "
        f"{dates.min():%d %b %Y} → {dates.max():%d %b %Y}")
    add(f"- **Total revenue (Sales):** ${sales.sum():,.0f}")
    add(f"- **Sales per line:** min ${sales.min():,.2f} · "
        f"mean ${sales.mean():,.2f} · max ${sales.max():,.2f}")
    add("")
    add("## Columns")
    add("")
    add("| # | Column | Dtype | Nulls | Unique |")
    add("|---|--------|-------|-------|--------|")
    for i, col in enumerate(raw.columns, 1):
        add(f"| {i} | {col} | {raw[col].dtype} | "
            f"{int(raw[col].isna().sum())} | {int(raw[col].nunique())} |")
    add("")
    add("## Key categoricals")
    add("")
    for col in ("Region", "Category", "Segment", "Ship Mode"):
        if col in raw.columns:
            vals = ", ".join(map(str, sorted(raw[col].dropna().unique())))
            add(f"- **{col}:** {vals}")
    add("")
    add("## Constraint confirmed")
    add("")
    numeric_measures = [c for c in raw.columns
                        if pd.api.types.is_numeric_dtype(raw[c])
                        and c not in ("Row ID", "Postal Code")]
    add(f"Numeric measures (excluding IDs/postal): **{numeric_measures or ['Sales']}**.")
    add("There is **no Profit / Quantity / Discount / review-text** column — so the "
        "forecast target is **revenue**, and prescriptive actions are revenue-based "
        "(see SYSTEM-ARCHITECTURE.md §0).")
    add("")
    add("_Generated by scripts/profile_data.py._")

    out = ROOT / "DATA_PROFILE.md"
    out.write_text("\n".join(lines) + "\n", encoding="utf-8")
    print(f"Wrote {out} ({len(raw):,} rows profiled).")


if __name__ == "__main__":
    main()
